### ISSUE TITLE
Install process went fine, no errors, but the chrome extension is lot loading. 

### ISSUE THREAD

**Issue by DerrickF** [andresdominguez/elementor#10]
![capture](https://cloud.githubusercontent.com/assets/11774386/7183500/05c6f478-e415-11e4-9c54-1b6e286fa8d9.PNG)

**Comment by andresdominguez** [comment]
When you start elementor a temporary protractor config file is created. If you look at the log you will see something like this:

```shell
Creating protractor configuration file
Starting protractor
Running command: [node /home/andres/.nvm/v0.11.16/lib/node_modules/elementor/node_modules/protractor-elementor/lib/cli.js --elementExplorer true --debuggerServerPort 6969 /tmp/protractor-conf115316-11669-10le421]
```
Where `/tmp/protractor-conf115316-11669-10le421` is the temporary file.

The configuration file looks like this:

```javascript
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',

  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: [
        '--load-extension=/home/andres/.nvm/v0.11.16/lib/node_modules/elementor/extension'
      ]
    }
  }
};
```

Can you send me the text of your configuration file? Maybe there is a space in the path and chrome cannot find the extension.

**Comment by BSUDerrickfink** [comment]
exports.config = {
  //directConnect: true,

  seleniumAddress: 'http://localhost:4444/wd/hub',

  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: [

'--load-extension=C:\Users\derrickfink\AppData\Roaming\npm\node_modules\elementor\extension'
      ]
    }
  }
};

On Thu, Apr 16, 2015 at 9:33 AM, Andres Dominguez <notifications@github.com>
wrote:

> When you start elementor a temporary protractor config file is created. If
> you look at the log you will see something like this:
>
> Creating protractor configuration file
> Starting protractor
> Running command: [node /home/andres/.nvm/v0.11.16/lib/node_modules/elementor/node_modules/protractor-elementor/lib/cli.js --elementExplorer true --debuggerServerPort 6969 /tmp/protractor-conf115316-11669-10le421]
>
> Where /tmp/protractor-conf115316-11669-10le421 is the temporary file.
>
> The configuration file looks like this:
>
> exports.config = {
>   seleniumAddress: 'http://localhost:4444/wd/hub',
>
>   capabilities: {
>     browserName: 'chrome',
>     chromeOptions: {
>       args: [
>         '--load-extension=/home/andres/.nvm/v0.11.16/lib/node_modules/elementor/extension'
>       ]
>     }
>   }
> };
>
> Can you send me the text of your configuration file? Maybe there is a
> space in the path and chrome cannot find the extension.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andresdominguez/elementor/issues/10#issuecomment-93765005>
> .
>



-- 
Derrick Fink,

Testing and Quality Assurance
Web & Mobile Applications
Boise State University
derrickfink@boisestate.edu

**Comment by andresdominguez** [comment]
I think I found a solution. I don't have my laptop with me (using my wife's laptop). I will get it fixed soon.

**Comment by DerrickF** [comment]
I was able to manually load the extension, without changing anything in the
manifest file, by loading the unpacked extension in the developer options.
It seems to work if you do it that way.

On Thu, Apr 16, 2015 at 6:43 PM, Andres Dominguez <notifications@github.com>
wrote:

> I think I found a solution. I don't have my laptop with me (using my
> wife's laptop). I will get it fixed soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andresdominguez/elementor/issues/10#issuecomment-93869445>
> .
>



-- 
Derrick Fink,

Student Web Developer
Web & Mobile Applications
Boise State University
derrickfink@boisestate.edu

**Comment by johnathanbeal** [comment]
I've found but am unable to load the manifest.json file

Failed to load extension from: ~
Could not load background script 'scripts/background.js'.

I also can't find the Chrome Automation Extension.

**Comment by andresdominguez** [comment]
There was a problem in the path of the file for the extension. It looked like this:

c:\path\to\extension

Now the path uses forward slash:

C:/path/to/extension

I tested it on Windows 7. Let me know if it works for you. I just pushed a new version: 1.0.8

**Comment by DerrickF** [comment]
Thanks!
I can confirm the the new build (1.0.8) is working great. 
Currently running Windows 8.1
