### ISSUE TITLE
Invalid selector generated

### ISSUE THREAD

**Issue by bootstraponline** [andresdominguez/elementor#12]
elementor generates invalid selectors. It looks like it's not escaping single quotes in objects properly.

`by.css('div[a-b="{id: 'c'}"]');`

**Comment by bootstraponline** [comment]
Another example:`by.css('div[ng-if=" a === 'b' "]')`

**Comment by andresdominguez** [comment]
Thank you for reporting this issue. 

Please update to 1.0.9
