### ISSUE TITLE
UI: "Locators" should clear and indicate loading while waiting for new locators.

### ISSUE THREAD

**Issue by fixermark** [andresdominguez/elementor#13]
When the currently-selected element updates, elementor does some analysis to determine what locators would apply to the selected element. If I then select a different element, the locators for the previous selection are still shown with no indication that Elementor is computing a new set (they update only once the computation is completed).

I recommend clearing the old Locators list (and possibly showing a "Loading" animation to indicate the list is expected to change soon).

**Comment by andresdominguez** [comment]
Please upgrade to 1.0.10
