### ISSUE TITLE
Elementor not displaying any locators on non Angular app

### ISSUE THREAD

**Issue by raducurteanu** [andresdominguez/elementor#18]
Hello Andres

I've tried your, very nice, tool on a non angular app. I followed the instructions you posted on youtube but it keeps saying: log: "Cannot find suggestions". 
I am trying it on a HTML element which has an id. But to be honest I tried on any type of element.
The interesting thing is that, when going back on the first tab, placing commands in the popup does what it's supposed to do.  

I am using:
protractor version: 2.1.0
elementor version: 1.0.10

As for logs, I must admit I don't know where to find them. So I will post you what I get in the terminal. For both elementor and selenium.

*elementor*

./node_modules/elementor/bin/elementor.js http://localhost/ten --nonAngular
Creating protractor configuration file
Starting protractor
Running command: [node /Applications/XAMPP/xamppfiles/htdocs/ten/node_modules/elementor/node_modules/protractor-elementor/lib/cli.js --elementExplorer true --debuggerServerPort 6969 /var/folders/t0/2jv1_2qd50d082bsf3qb74b00000gn/T/protractor-conf115429-10979-2se8qn]
Using the selenium server at http://localhost:4444/wd/hub
Starting WebDriver debugger in a child process. Pause is still beta, please report issues at github.com/angular/protractor

Type <tab> to see a list of locator strategies.
Use the `list` helper function to find elements by strategy:
  e.g., list(by.binding('')) gets all bindings.
Server listening on 127.0.0.1:6969
Done starting protractor
Starting elementor
Elementor is listening on http://localhost:13000
Running elementor in non-angular mode.
Getting page at: http://localhost/ten
Connected. Sending command: browser.ignoreSynchronization = true;browser.get('http://localhost/ten');
Elementor is ready!

*selenium*

./node_modules/protractor/bin/webdriver-manager start
seleniumProcess.pid: 10976
00:02:58.903 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to /Applications/XAMPP/xamppfiles/htdocs/ten/node_modules/protractor/selenium/chromedriver
00:02:58.953 INFO - Java: Oracle Corporation 25.31-b07
00:02:58.953 INFO - OS: Mac OS X 10.10.3 x86_64
00:02:58.963 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
00:02:59.075 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: MAC
00:02:59.129 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
00:02:59.131 INFO - Version Jetty/5.1.x
00:02:59.134 INFO - Started HttpContext[/selenium-server,/selenium-server]
00:02:59.162 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@7e0babb1
00:02:59.163 INFO - Started HttpContext[/wd,/wd]
00:02:59.163 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
00:02:59.163 INFO - Started HttpContext[/,/]
00:02:59.168 INFO - Started SocketListener on 0.0.0.0:4444
00:02:59.169 INFO - Started org.openqa.jetty.jetty.Server@6e2c634b
00:03:04.588 INFO - Executing: [new session: Capabilities [{browserName=chrome, chromeOptions={args=[--load-extension=/Applications/XAMPP/xamppfiles/htdocs/ten/node_modules/elementor/extension]}}]])
00:03:04.609 INFO - Creating a new session for Capabilities [{browserName=chrome, chromeOptions={args=[--load-extension=/Applications/XAMPP/xamppfiles/htdocs/ten/node_modules/elementor/extension]}}]
Starting ChromeDriver 2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f) on port 44343
Only local connections are allowed.
00:03:06.423 INFO - Done: [new session: Capabilities [{browserName=chrome, chromeOptions={args=[--load-extension=/Applications/XAMPP/xamppfiles/htdocs/ten/node_modules/elementor/extension]}}]]
00:03:08.933 INFO - Executing: [set script timeoutt: 11000])
00:03:08.943 INFO - Done: [set script timeoutt: 11000]
00:03:08.968 INFO - Executing: [get: http://localhost/ten])
00:03:10.155 INFO - Done: [get: http://localhost/ten]

This is basically all I can give you. It pretty much stays like this no matter what you do in the Chrome developer tools.

I hope you find the time to find a fix for this. Elementor really saves a lot of time when writing E2E tests.

All the best,
Radu

**Comment by andresdominguez** [comment]
Thank you for reporting the issue. I will take a look tomorrow.

**Comment by andresdominguez** [comment]
I was able to reproduce the issue. I will try to fix it over the weekend. I will ping you once it gets fixed.

**Comment by raducurteanu** [comment]
That would be great. Thank you for your work.

**Comment by dcypherthis** [comment]
Hello Andres,

Have you had a chance to make any progress on this issue?  I'd love to use this awesome tool across all my app, not just angular.

Let me know if I can help!

**Comment by ryanbowden** [comment]
Just wondering if you ever fixed this issue?

Just come across this service and would love to use it.

**Comment by andresdominguez** [comment]
I just published 1.1.0 to npm. Now you should be able to get suggestions for non-angular pages.

Please let me know if you find any problems.

**Comment by mmorenoivy** [comment]
Hi andres,

I am also having the same issue as raducurteanu. I am using angular app, though the suggestions gets printed into the console. Thanks

**Comment by andresdominguez** [comment]
@mmorenoivy try the following:

* Get the latest version of elementor 
```shell
$ elementor --version
1.1.0
```
* Use the **--nonAngular** flag
```shell
$ elementor https://google.com --nonAngular
```
* Open a second tab pointing to the same page as the same tab. Open the developer console on the second tab. Click on the elements tab and then select the "Protractor" pane.
* Select an element

You should get suggestions

**Comment by mmorenoivy** [comment]
@andresdominguez  thanks for the response. I had the 1.1.0 version and i used the --nonAngular flag, and it is working. Thanks so much, this is a very good help!
