### ISSUE TITLE
Starting protractor fails silently

### ISSUE THREAD

**Issue by kenhowardpdx** [andresdominguez/elementor#20]
Running on Windows 8.1
Protractor 2.1.0
Elementor 1.0.10

I initialize elementor, then nothing happens.

```
$ elementor https://angularjs.org
Creating protractor configuration file
Starting protractor
Running command: [node c:\Users\Ken Howard\AppData\Roaming\npm\node_modules\elementor\node_modules\protractor-elementor\lib\cli.js --elementExplorer true --debuggerServerPort 6969 C:\Users\KENHOW~1\AppData\Local\Temp\protractor-conf115516-8860-1r47b0b]
```

I have inspected the `Temp` directory but the configuration file doesn't exist.

**Comment by andresdominguez** [comment]
Thank you for filing the bug.

Sometimes node cannot find a file when there is a space in the path. Your username has a space.

I will try to escape the space character and test it. I do not have windows 8, but I can test with a win 7 machine.

The temp file will get deleted when when you shutdown node. Can you check if the file exists before killing the process?

**Comment by kenhowardpdx** [comment]
I just commented out this line: https://github.com/andresdominguez/elementor/blob/master/lib/config-helper.js#L13

The file is being created... In fact, TWO files are being created. The contents of both is identical.

**Comment by MerlinMartel** [comment]
Similar for me
Windows 10
Protractor : 4.0.13
Elementor : 2.1.0

I run this : 

```
elementor https://angularjs.org
Creating protractor configuration file
Starting protractor
Running command: [node C:\Program Files\nodejs\node_modules\elementor\node_modules\protractor\built\cli.js --elementExplorer true --debuggerServerPort 6969 C:\Users\Merlin\AppData\Loc
al\Temp\protractor-conf117016-14104-we1pj0.tu6a5g66r]
```
But nothing happen. Chrome is not opening. 
Configuration file is not there.
If this related to the space in "Program files" ?

thx
