### ISSUE TITLE
Can't get Dev Tools extension to work

### ISSUE THREAD

**Issue by dmackerman** [andresdominguez/elementor#22]
First off, amazing tool. This is a godsend for trying to write E2E tests.

I tried following the instructions about Duplicating the tab, but whatever I do, the "Protractor" tab is always either blank, or says "No Properties"

**Comment by virtser** [comment]
Same here. :(

**Comment by anu-01** [comment]
Create a duplicate tab and start using elementor, it loads suggestions.
