### ISSUE TITLE
elementor - closing dev tools

### ISSUE THREAD

**Issue by ryanbowden** [andresdominguez/elementor#25]
Hi, 

I have set up with the new version for a nonAngular application,  but when i select an element it closes the dev tools and outputs the results in the console. I am guessing there is some sort of error there or is this supposed to happen?

**Comment by andresdominguez** [comment]
Open a new tab with the same page as the first tab. Use the developer tools on the second tab to get suggestions. 

Protractor uses the developer tools to communicate with the browser. It cannot be open while protractor is running. That is why the console gets closed.

**Comment by kcampion** [comment]
+1
