### ISSUE TITLE
Elementor Not able to load the URL on chrome that is being passed.( "Finding suggestions")

### ISSUE THREAD

**Issue by adityagautam** [andresdominguez/elementor#32]
<img width="1021" alt="screen shot 2016-03-22 at 2 11 57 am" src="https://cloud.githubusercontent.com/assets/4173001/13943565/e013a674-efd3-11e5-9b17-a5793df64efe.png">
1) webdriver-manager start
2) elementor https://angular.github.io/protractor/#/api

Google chrome opens with data:, in the URL box.( See the screen shot). Then if I try to manually enter the following url "https://angular.github.io/protractor/#/api" and then duplicate it. Still I dont get locators when I try to inspect the element.

My guess is elementor should load up the browser with the URL that I am passing. But for some reason its not doing that

Elementor version 1.1.0
Protractor version-3.2.1

**Comment by foxinni** [comment]
+1

**Comment by andresdominguez** [comment]
Hello:

Can you try to upgrade to the latest version of elementor (2.0.0)?

**Comment by ikabodd** [comment]
+1 Any update on a fix for this issue?

**Comment by adityagautam** [comment]
v 2.0.0 works fine. Thanks for addressing this issue.

**Comment by adityagautam** [comment]
This issue is happening again with elementor 2.1.0 and protractor 5.1.0.

**Comment by adityagautam** [comment]
Closing this issue. As new versions are working fine.

**Comment by saadqc** [comment]
Still having this issue. Tried with 2.0.0 & 2.1.0
any suggestions?

**Comment by DivyaMadari17** [comment]
I still face the same issue with 2.1.0. Suggestions please.

**Comment by saadqc** [comment]
@DivyaMadari17 : What version of node are you using?

**Comment by JemiArtistaa** [comment]
Facing the same problem with 2.1.0. Is there any solution ???? Please provide feedback asap.

**Comment by JemiArtistaa** [comment]
i am using node v8.1.0

**Comment by eabid-cc** [comment]
Is this issue resolved? I'm still facing it.
Node version: 8.2.1
Elementor version: 2.1.0
Protractor version: 5.1.2

**Comment by rjcreatto** [comment]
I was having the same issue and what worked for me, remove the version 8.3.0 and install v7.8.0.

**Comment by DivyaMadari17** [comment]
I am using 8.1.2

**Comment by waleedwaseem** [comment]
You can switch back to the node version that was functional with elementor using n or nvm e.g. 6.14.1. Once you are back to your old version, Run elementor which will open the browser. Once the browser is open, switch back to the node version in which your app is built and run your application. It will resolve the "Finding suggestions" issue.

Hope it helped. :)
