### ISSUE TITLE
Is there a way to run elementor for non-angular apps?

### ISSUE THREAD

**Issue by stevermeister** [andresdominguez/elementor#6]

**Comment by andresdominguez** [comment]
Launch elementor and then, from the command line enter:

```shell
browser.ignoreSynchronization = true
```

There is a PR that includes this feature. I will merge it and then release a new version.

**Comment by stevermeister** [comment]
@andresdominguez ,

thank you for quick response! 
and thank you very much for such a nice addition for protractor. 

I've written the [post](http://stepansuvorov.com/blog/2015/01/elementor-%D0%B4%D0%B5%D0%BB%D0%B0%D0%B5%D1%82-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81-protractor-%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%BD%D0%B5%D0%B5/)(it's in Russian) about your tool on my blog, so that was already question from readers. :)

**Comment by andresdominguez** [comment]
Amazing! Thank you for the blog post!

**Comment by andresdominguez** [comment]
I just pushed a new version to npm. Try launching elementor 

```shell
elementor https://google.com --nonAngular
```

Let me know if it works.

**Comment by stevermeister** [comment]
great! thanks a lot!
