### ISSUE TITLE
Failed to open socket on port 5858, waiting 1000 ms before retrying

### ISSUE THREAD

**Issue by ch0wdan** [andresdominguez/elementor#8]
Hey,

With the new version(1.0.4) published in npm, i'm no longer able to boot up elementor. im seeing it start the webdriver, it spins up a new chrome instance, but then closes out. 

Heres what im seeing in cmd(running mac osx):

Type <tab> to see a list of locator strategies.
Use the `list` helper function to find elements by strategy:
  e.g., list(by.binding('')) gets all bindings.
Server listening on 127.0.0.1:6969
Done starting protractor
Elementor is listening on http://localhost:13000
Getting page at: http://localhost:9000
Connected. Sending command: browser.get('http://localhost:9000')
Failed to open socket on port 5858, waiting 1000 ms before retrying
Failed to open socket on port 5858, waiting 1000 ms before retrying

**Comment by andresdominguez** [comment]
Thank you for the feedback. The code to open the URL may be buggy.

Can you try to launch elementor with no arguments and then enter the url in the browser? Does it work when you don't provide the url?

**Comment by ch0wdan** [comment]
@andresdominguez - Launching Elementor with just "elementor" also results in this same issue. 

I've also tried launching to my localhost with "--chrome" and also with just 'elementor --chrome".

So far i'm not able to get the browser to stay open. Also tried re-updating webdriver however seems like thats not the issue either.

**Comment by ch0wdan** [comment]
accidentally closed this. Issue still present

**Comment by andresdominguez** [comment]
Maybe there is another process running in the background that didn't die.

Try to do a:

```shell
ps -ef | grep protractor
```

And kill any processes that were left open. 

I will add code to make sure that the protractor process goes down when you kill elementor.

**Comment by ch0wdan** [comment]
@andresdominguez  - Good catch. Were currently using "grunt serve" to serve our webapp. That was the conflicting instance.

For anyone in the future reading this. If your issuing this issue and are also using grunt for your app - shut down your grunt serve instance, launch elementor THEN start your grunt instance.
