### ISSUE TITLE
"Error: Angular could not be found on the page" even with --nonAngular

### ISSUE THREAD

**Issue by Rleahy22** [andresdominguez/elementor#9]
Using the 1.0.4 release trying to use elementor on non-Angular pages fails because it could not find Angular even when I supply the nonAngular flag.

**Comment by andresdominguez** [comment]
Hello @Rleahy22 

I think I broke the --nonAngular feature when I refactored elementor last weekend.

I will add it back tonight.

In the meantime, run elementor with no arguments. When the browser launches open the popup and enter:

```javascript
browser.ignoreSynchronization = true;
```

Andres

**Comment by Rleahy22** [comment]
Great thank you!

**Comment by andresdominguez** [comment]
Done. Please get 1.0.5
